#!/bin/bash

NEW_HDFS_BACKUP_PLUGIN="${PARCELS_ROOT}/${PARCEL_DIRNAME}/lib"

if [ -n "${HDFS_BACKUP_PLUGINS}" ]; then
  export HDFS_BACKUP_PLUGINS="${HDFS_BACKUP_PLUGINS}:${NEW_HDFS_BACKUP_PLUGIN}"
else
  export HDFS_BACKUP_PLUGINS="${NEW_HDFS_BACKUP_PLUGIN}"
fi
